# general
exp_name: example_experiment
run_name: run_debug_delete_me
max_epoch: 10
log_every_n_steps: 1

# set to null to avoid setting a seed (can speed up GPU computation, but
# results will not be reproducible)
seed: 1234

# data
data:
  batch_size: 32
  num_workers: 4
  max_atom: 64

# architecture
spatial_dimension: 3
model:
  score_network:
    hidden_dimensions: [8, 16, 32]  # dimensions of the hidden layers. Length of array determines number of layers
  noise:
    total_time_steps: 10
    sigma_min: 0.005  # default value
    sigma_max: 0.5  # default value

# optimizer
optimizer:
  name: adam
  learning_rate: 0.001

# early stopping
early_stopping:
  metric: val_loss
  mode: min
  patience: 100

model_checkpoint:
  monitor: val_loss
  mode: min

logging:
  - tensorboard
  - comet
