# general
exp_name: example_experiment
run_name: run_debug_delete_me
max_epoch: 10
log_every_n_steps: 100

# set to null to avoid setting a seed (can speed up GPU computation, but
# results will not be reproducible)
seed: 1234

# data
data:
  batch_size: 128
  num_workers: 0
  max_atom: 8

# architecture
spatial_dimension: 3
model:
  score_network:
    n_hidden_dimensions: 3
    hidden_dimensions_size: 512
  noise:
    total_time_steps: 100
    sigma_min: 0.005  # default value
    sigma_max: 0.5  # default value

# optimizer and scheduler
optimizer:
  name: adamw
  learning_rate: 0.001
  weight_decay: 1.0e-6

scheduler:
  name: ReduceLROnPlateau
  factor: 0.6
  patience: 10

# early stopping
early_stopping:
  metric: validation_epoch_loss
  mode: min
  patience: 100

model_checkpoint:
  monitor: validation_epoch_loss
  mode: min

# Sampling from the generative model
diffusion_sampling:
  noise:
    total_time_steps: 100
    sigma_min: 0.005  # default value
    sigma_max: 0.5  # default value
  sampling:
    spatial_dimension: 3
    number_of_corrector_steps: 1
    number_of_atoms: 64
    number_of_samples: 128
    sample_every_n_epochs: 1
    cell_dimensions: [5.43, 5.43, 5.43]

logging:
  - csv
  - tensorboard
  - comet
