# general
exp_name: mlp_example
run_name: run_debug_delete_me
max_epoch: 10
log_every_n_steps: 1
gradient_clipping: 0
accumulate_grad_batches: 1  # make this number of forward passes before doing a backprop step

# set to null to avoid setting a seed (can speed up GPU computation, but
# results will not be reproducible)
seed: 1234

elements: [Si]

# data
data:
  batch_size: 1024
  num_workers: 0
  max_atom: 8
  use_fixed_lattice_parameters: True
  noise:
    total_time_steps: 100
    sigma_min: 0.005  # default value
    sigma_max: 0.5  # default value'

# architecture
spatial_dimension: 3
model:
  loss: # Only the relative coordinates loss will matter.
    coordinates:
      algorithm: mse
      lambda_weight: 1.0
    atom_types:
      algorithm: d3pm
      lambda_weight: 0.0
      ce_weight: 1.0
    lattice_parameters:
      algorithm: mse
      lambda_weight: 0.0
  score_network:
    architecture: mlp
    spatial_dimension: 3
    num_atom_types: 1
    number_of_atoms: 8
    n_hidden_dimensions: 'orion~choices([1, 2, 3, 4])'
    hidden_dimensions_size: 'orion~choices([16, 32, 64])'
    noise_embedding_dimensions_size: 16
    atom_type_embedding_dimensions_size: 16
    relative_coordinates_embedding_dimensions_size: 32
    time_embedding_dimensions_size: 16
    lattice_parameters_embedding_dimensions_size: 8
    conditional_prob: 'orion~choices([0.0, 0.25, 0.5])'
    condition_embedding_size: 'orion~choices([32, 64])'
    use_permutation_invariance: False


# optimizer and scheduler
optimizer:
  name: adamw
  learning_rate: 'orion~loguniform(1e-6, 1e-3)'
  weight_decay: 1.0e-6

scheduler:
  name: ReduceLROnPlateau
  factor: 0.1
  patience: 3

# early stopping
early_stopping:
  metric: validation_epoch_loss
  mode: min
  patience: 10

model_checkpoint:
  monitor: validation_epoch_loss
  mode: min

# A callback to check the loss vs. sigma
loss_monitoring: 
  number_of_bins: 50
  sample_every_n_epochs: 2

# Sampling from the generative model
diffusion_sampling:
  noise:
    total_time_steps: 100
    sigma_min: 0.001  # default value
    sigma_max: 0.5  # default value
  sampling:
    algorithm: predictor_corrector
    spatial_dimension: 3
    num_atom_types: 1
    number_of_corrector_steps: 1
    number_of_atoms: 8
    number_of_samples: 16
    sample_batchsize: None
    sample_every_n_epochs: 2
    cell_dimensions: [5.43, 5.43, 5.43]

logging:
  - comet
#- tensorboard
#- csv
