active_learning_data:
  _target_: crystal_diffusion.active_learning_loop.activelearning_dataclasses.ActiveLearningDataArguments
  training_data_dir: /Users/simonb/ic-collab/courtois_collab/crystal_diffusion/data/al_baseline_dev/v1/
  evaluation_data_dir: /Users/simonb/ic-collab/courtois_collab/crystal_diffusion/data/al_baseline_dev/v1/
  output_dir: /Users/simonb/ic-collab/courtois_collab/crystal_diffusion/experiments/benchmark/debug/

mlip:
  _target_: crystal_diffusion.models.mlip.mtp.MTPWithMLIP3
  mtp_args:
    _target_: crystal_diffusion.models.mlip.mtp.MTPArguments
    mlip_path: /Users/simonb/ic-collab/courtois_collab/crystal_diffusion/mlip-3/  # path to MLIP3 library
    name: None  # MTP
    param: None
    unfitted_mtp: 08.almtp  # Define the initial mtp file. Default to 08g.amltp
    fitted_mtp_savedir: /Users/simonb/ic-collab/courtois_collab/crystal_diffusion/experiments/benchmark/debug/mtp/  # save directory for the fitted MTP. Defaults to '../' (current wd)
    max_dist: 5.0  # The actual radial cutoff. Defaults to 5.
    radial_basis_size: 8  # Relevant to number of radial basis function. Defaults to 8.
    max_iter: 1000  # The number of maximum iteration. Defaults to 1000.
    energy_weight: 1.0  # The weight of energy. Defaults to 1
    force_weight: 1e-2  # The weight of forces. Defaults to 1e-2
    stress_weight: 1e-3  # The weight of stresses. Zero-weight can be assigned. Defaults to 1e-3.
    init_params: same  # how to initialize parameters if a potential was not pre-fitted: "same" or "random".
    scale_by_force: 0  # If > 0 then configurations near equilibrium get more weight. Defaults to 0.
    bfgs_conv_tol: 1e-3  # Stop training if error dropped by a factor smaller than this over 50 BFGS iterations.
    weighting: vibration  # How to weight configuration with different sizes relative to each other.
    # Choose from "vibrations", "molecules" and "structures". Defaults to "vibration".

structure_evaluation:
  _target_: crystal_diffusion.active_learning_loop.activelearning_dataclasses.StructureEvaluationArguments
  evaluation_criteria: 'nbh_grades'  # maxvol coefficient name in the mtp outputs
  criteria_threshold: 10.0  # atoms with a MaxVol value under this value are considered bad
  # number_of_structures: None  # alternatively, take the N worst samples from the evaluation set
  extraction_radius: 3  # extract atoms within this radius from the worst atom in a structure

repainting_model:
  _target_: crystal_diffusion.active_learning_loop.activelearning_dataclasses.RepaintingArguments
  model: dev_dummy  # placeholder for development

oracle:
  _target_: crystal_diffusion.active_learning_loop.oracle.LAMMPS_for_active_learning

initial_df_save_path: /Users/simonb/ic-collab/courtois_collab/crystal_diffusion/experiments/active_learning_benchmark/debug/before_tuning.csv
updated_df_save_path: /Users/simonb/ic-collab/courtois_collab/crystal_diffusion/experiments/active_learning_benchmark/debug/after_tuning.csv