# general
exp_name: example_narval
run_name: run1
max_epoch: 3
log_every_n_steps: 1
# fast_dev_run: True
# set to null to avoid setting a seed (can speed up GPU computation, but
# results will not be reproducible)
seed: 1234
gradient_clipping: 0

# data
data:
  batch_size: 128
  num_workers: 0
  max_atom: 8

# architecture
spatial_dimension: 3
model:
  score_network:
    n_hidden_dimensions: 2
    hidden_dimensions_size: 64
  noise:
    total_time_steps: 10
    sigma_min: 0.005  # default value
    sigma_max: 0.5  # default value

# optimizer
optimizer:
  name: adam
  learning_rate: 0.001

# early stopping
early_stopping:
  metric: validation_epoch_loss
  mode: min
  patience: 100

model_checkpoint:
  monitor: validation_epoch_loss
  mode: min

logging:
  - csv
  - comet
