# general
exp_name: diffusion_mace_example
run_name: run_debug_delete_me
max_epoch: 10
log_every_n_steps: 1
gradient_clipping: 0.1
accumulate_grad_batches: 1  # make this number of forward passes before doing a backprop step

# set to null to avoid setting a seed (can speed up GPU computation, but
# results will not be reproducible)
seed: 1234

elements: [Si]

# data
data:
  batch_size: 512
  num_workers: 0
  max_atom: 8

# architecture
spatial_dimension: 3
model:
  loss:
    coordinates_algorithm: mse
  score_network:
    architecture: diffusion_mace
    num_atom_types: 1
    number_of_atoms: 8
    r_max: 5.0
    num_bessel: 8
    num_polynomial_cutoff: 5
    num_edge_hidden_layers: 0
    edge_hidden_irreps: 8x0e
    max_ell: 2
    interaction_cls: RealAgnosticResidualInteractionBlock
    interaction_cls_first: RealAgnosticInteractionBlock
    num_interactions: 2
    hidden_irreps: 8x0e + 8x1o
    mlp_irreps: 8x0e
    number_of_mlp_layers: 0
    avg_num_neighbors: 1
    correlation: 3
    gate: silu
    radial_MLP: [8, 8, 8]
    radial_type: gaussian
    conditional_prob: 0.0
    conditional_gamma: 2
    condition_embedding_size: 64
    use_batchnorm: False
    tanh_after_interaction: True
  noise:
    total_time_steps: 100
    sigma_min: 0.001  # default value
    sigma_max: 0.5  # default value'

# optimizer and scheduler
optimizer:
  name: adamw
  learning_rate: 0.001
  weight_decay: 1.0e-6

scheduler:
  name: ReduceLROnPlateau
  factor: 0.1
  patience: 3

# early stopping
early_stopping:
  metric: validation_epoch_loss
  mode: min
  patience: 10

model_checkpoint:
  monitor: validation_epoch_loss
  mode: min

# Sampling from the generative model
diffusion_sampling:
  noise:
    total_time_steps: 100
    sigma_min: 0.001  # default value
    sigma_max: 0.5  # default value
  sampling:
    algorithm: predictor_corrector
    spatial_dimension: 3
    number_of_atoms: 8
    number_of_samples: 16
    sample_every_n_epochs: 5
    record_samples: True
    cell_dimensions: [5.43, 5.43, 5.43]

oracle:
  name: lammps
  sw_coeff_filename: Si.sw

logging:
  #  - csv
  - tensorboard
    #- comet
