exp_name: dev_debug
run_name: run1
max_epoch: 50
log_every_n_steps: 1
gradient_clipping: 0.0
accumulate_grad_batches: 1  # make this number of forward passes before doing a backprop step


# set to null to avoid setting a seed (can speed up GPU computation, but
# results will not be reproducible)
seed: 1234

# data
data:
  batch_size: 128
  num_workers: 8
  max_atom: 64

# architecture
spatial_dimension: 3
model:
  score_network:
    architecture: egnn
    n_layers: 4
    coordinate_hidden_dimensions_size: 128
    coordinate_n_hidden_dimensions: 4
    coords_agg: "mean"
    message_hidden_dimensions_size: 128
    message_n_hidden_dimensions: 4
    node_hidden_dimensions_size: 128
    node_n_hidden_dimensions: 4
    attention: False
    normalize: True
    residual: True
    tanh: False
    edges: fully_connected
  noise:
    total_time_steps: 1000
    sigma_min: 0.0001
    sigma_max: 0.2
    corrector_step_epsilon: 2.0e-7

# optimizer and scheduler
optimizer:
  name: adamw
  learning_rate: 0.001
  weight_decay: 5.0e-8


scheduler:
  name: CosineAnnealingLR
  T_max: 50
  eta_min: 0.0

# early stopping
early_stopping:
  metric: validation_epoch_loss
  mode: min
  patience: 100

model_checkpoint:
  monitor: validation_ks_distance_structure
  mode: min

# Sampling from the generative model
diffusion_sampling:
  noise:
    total_time_steps: 1000
    sigma_min: 0.0001
    sigma_max: 0.2
    corrector_step_epsilon: 2.0e-7
  sampling:
    algorithm: predictor_corrector
    sample_batchsize: 128
    spatial_dimension: 3
    number_of_corrector_steps: 1
    number_of_atoms: 64
    number_of_samples: 32
    record_samples: False
    cell_dimensions: [10.86, 10.86, 10.86]
  metrics:
    compute_energies: True
    compute_structure_factor: True
    structure_factor_max_distance: 10.0

sampling_visualization:
  record_every_n_epochs:  1
  first_record_epoch: 1
  record_trajectories: False
  record_energies: True
  record_structure: True


logging:
  - comet
